PLAYER_REGISTRATION_REWARD_PARAM_NAME = 'playerRegistration'
PLAYER_REGISTRATION_REWARD_TITLE = 'Quiz Registration'

RESPONSE_A_REWARD_TITLE = 'Response A'
RESPONSE_B_REWARD_TITLE = 'Response B'
RESPONSE_C_REWARD_TITLE = 'Response C'
RESPONSE_D_REWARD_TITLE = 'Response D'

REGISTRATION_REWARD_STATUS_FULFILLED = "FULFILLED"
REGISTRATION_REWARD_STATUS_CANCELLED = "CANCELLED"
