PLAYER_REGISTRATION_REWARD_PARAM_NAME = 'playerRegistration'
PLAYER_REGISTRATION_REWARD_TITLE = 'Quiz Registration'

REGISTRATION_REWARD_STATUS_FULFILLED = "FULFILLED"
REGISTRATION_REWARD_STATUS_CANCELLED = "CANCELLED"
